### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/github-task-status#1]
#### Idea

Automatically build a badge based on the amount of completion of tasks for a GitHub comment. This comes from this issue: https://github.com/ipfs/pm/issues/111
#### Roadmap
- [x] Init repo
- [x] Use the CLI tool to grab the first comment from an issue
- [x] Parse that issue to grab a list of tasks
- [x] Parse completed tasks
- [x] Return a percentage of finished tasks
- [x] Wrap the finished tasks in an html badge
- [x] Enable to grab from a list of URLs to check
- [ ] Set up as a server-side task that runs on a cron-job
- [ ] Enable for sublists
  - [ ] Like this one
- [ ] Enable for comments that aren't the first in the issue
- [ ] Check completion of tasks from issues linked in one issue
- [ ] Make a GitHub bot to add issues to a list

If you have more suggestions, add them here!

**Comment by RichardLitt** [comment]
Currently: 

``` sh
node cli.js https://api.github.com/repos/RichardLitt/github-task-status/issues/1
{ done: 4, undone: 3 }
```

Will hack more on this tomorrow.

**Comment by RichardLitt** [comment]
Now:

```
node cli.js RichardLitt/github-task-status/issues/3
{ done: 2,
  undone: 2,
  progressio: 'http://progressed.io/bar/50',
  progressioTitle: 'http://progressed.io/bar/50?title=2/4' }
```
